const languages_list=[
    'Auto-detect',
    'Afrikaans',
    'Amharic',
    'Arabic',
    'Assamese',
    'Azerbaijani',
    'Bulgarian',
    'Bangla',
    'Bosnian',
    'Catalan',
    'Czech',
    'Welsh',
    'Danish',
    'German',
    'Greek',
    'English',
    'Spanish',
    'Estonian',
    'Persian',
    'Finnish',
    'Filipino',
    'Fijian',
    'French',
    'French (Canada)',
    'Irish',
    'Gujarati',
    'Hebrew',
    'Hindi',
    'Croatian',
    'Haitian Creole',
    'Hungarian',
    'Armenian',
    'Indonesian',
    'Icelandic',
    'Italian',
    'Inuktitut',
    'Japanese',
    'Kazakh',
    'Khmer',
    'Kurdish (Northern)',
    'Kannada',
    'Korean',
    'Kurdish (Central)',
    'Lao',
    'Lithuanian',
    'Latvian',
    'Malagasy',
    'Maori',
    'Malayalam',
    'Marathi',
    'Malay',
    'Maltese',
    'Hmong Daw',
    'Myanmar',
    'Norwegian',
    'Nepali',
    'Dutch',
    'Odia',
    'Querétaro Otomi',
    'Punjabi',
    'Polish',
    'Dari',
    'Pashto',
    'Portuguese (Brazil)',
    'Portuguese (Portugal)',
    'Romanian',
    'Russian',
    'Slovak',
    'Slovenian',
    'Samoan',
    'Albanian',
    'Serbian (Cyrillic)',
    'Serbian (Latin)',
    'Swedish',
    'Swahili',
    'Tamil',
    'Telugu',
    'Thai',
    'Tigrinya',
    'Klingon (Latin)',
    'Klingon (pIqaD)',
    'Tongan',
    'Turkish',
    'Tahitian',
    'Ukrainian',
    'Urdu',
    'Vietnamese',
    'Yucatec Maya',
    'Cantonese (Traditional)',
    'Chinese Simplified',
    'Chinese Traditional'
  ]
  module.exports=languages_list;